# Compile both programs
all: task1 task2

# Compile Task 1
task1: task1.c
	gcc task1.c -o task1

# Compile Task 2
task2: task2.c
	gcc task2.c -o task2

# Remove compiled programs
clean:
	rm -f task1 task2